import codecs
from tomlkit import comment
from tomlkit import document
from tomlkit import table
from tomlkit import dumps


doc = document()
doc.add(comment('fb2c configuration file'))
doc.add(comment('Generated by Libro'))

logger = table()

logger_console = table()
logger_console.add('level', 'normal')

logger_file = table()
logger_file.add('level', 'debug')
logger_file.add('destination', 'fb2c.log')
logger_file.add('mode', 'overwrite')

logger.add('console', logger_console)
logger.add('file', logger_file)

document = table()

document.add('remove_png_transparency', True)
document.add('title_format', '{(#abbrseries{ #padnumber}) }#title')
document.add('series_number_positions', 2)
document.add('author_format', '#l{ #f{ #m}}')
document.add('insert_soft_hyphen', False)


sendtokindle = table()
fb2mobi = table()

doc.add('logger', logger)
doc.add('document', document)
doc.add('sendtokindle', sendtokindle)
doc.add('fb2mobi', fb2mobi)

with codecs.open('config.toml', mode='w', encoding='utf-8') as f:
    f.write(dumps(doc))
