# -*- coding: utf-8 -*-

tag_translate = {
	'sf_history': 'Альтернативная история',
	'sf_action': 'Боевая фантастика',
	'sf_epic': 'Эпическая фантастика',
	'sf_heroic': 'Героическая фантастика',
	'sf_detective': 'Детективная фантастика',
	'sf_cyberpunk': 'Киберпанк',
	'sf_space': 'Космическая фантастика',
	'sf_social': 'Социальная фантастика',
	'sf_horror': 'Ужасы и мистика',
	'sf_humor': 'Юмористическая фантастика',
	'sf_fantasy': 'Фэнтези',
	'sf': 'Научная фантастика',
	'child_sf': 'Детская фантастика',
	'det_classic': 'Классический детектив',
	'det_police': 'Полицейский детектив',
	'det_action': 'Боевики',
	'det_irony': 'Иронический детектив',
	'det_history': 'Исторический детектив',
	'det_espionage': 'Шпионский детектив',
	'det_crime': 'Криминальный детектив',
	'det_political': 'Политический детектив',
	'det_maniac': 'Маньяки',
	'det_hard': 'Крутой детектив',
	'thriller': 'Триллеры',
	'detective': 'Детектив',
	'sf_detective': 'Детективная дантастика',
	'child_det': 'Детские остросюжетные',
	'love_detective': 'Остросюжетные любовные романы',
	'prose': 'Проза',
	'prose_classic': 'Классическая проза',
	'prose_history': 'Историческая проза',
	'prose_contemporary': 'Современная проза',
	'prose_counter': 'Контркультура',
	'prose_rus_classic': 'Русская классика',
	'prose_su_classics': 'Советская классика',
	'humor_prose': 'Юмористическая проза',
	'child_prose': 'Детская проза',
	'love': 'Любовные романы',
	'love_contemporary': 'Современные любовные романы',
	'love_history': 'Исторические любовные романы',
	'love_detective': 'Остросюжетные любовные романы',
	'love_short': 'Короткие любовные романы',
	'love_erotica': 'Эротика',
	'adv_western': 'Вестерны',
	'adv_history': 'Исторические приключения',
	'adv_indian': 'Приключения: индейцы',
	'adv_maritime': 'Морские приключения',
	'adv_geo': 'Путешествия и география',
	'adv_animal': 'Природа и животные',
	'adventure': 'Приключения: прочее',
	'child_adv': 'Детские приключения',
	'children': 'Детское',
	'child_tale': 'Сказки',
	'child_verse': 'Детские стихи',
	'child_prose': 'Детская проза',
	'child_sf': 'Детская фантастика',
	'child_det': 'Детские остросюжетные',
	'child_adv': 'Детские рриключения',
	'child_education': 'Детская образовательная литература',
	'children': 'Детское: ррочее',
	'poetry': 'Поэзия',
	'dramaturgy': 'Драматургия',
	'humor_verse': 'Юмористические стихи',
	'child_verse': 'Детские стихи',
	'antique_ant': 'Античная литература',
	'antique_european': 'Европейская старинная литература',
	'antique_russian': 'Древнерусская литература',
	'antique_east': 'Древневосточная литература',
	'antique_myths': 'Мифы. Легенды. Эпос',
	'antique': 'Старинная литература: прочее',
	'sci_history': 'История',
	'sci_psychology': 'Психология',
	'sci_culture': 'Культурология',
	'sci_religion': 'Религиоведение',
	'sci_philosophy': 'Философия',
	'sci_politics': 'Политика',
	'sci_business': 'Деловая литература',
	'sci_juris': 'Юриспруденция',
	'sci_linguistic': 'Языкознание',
	'sci_medicine': 'Медицина',
	'sci_phys': 'Физика',
	'sci_math': 'Математика',
	'sci_chem': 'Химия',
	'sci_biology': 'Биология',
	'sci_tech': 'Технические',
	'science': 'Научно-образовательная: прочее',
	'adv_animal': 'Природа и животные',
	'comp_www': 'Интернет',
	'comp_programming': 'Программирование',
	'comp_hard': 'Компьютерное железо',
	'comp_soft': 'Программы',
	'comp_db': 'Базы Данных',
	'comp_osnet': 'ОС и Сети',
	'computers': 'Компьютеры: прочее',
	'ref_encyc': 'Энциклопедии',
	'ref_dict': 'Словари',
	'ref_ref': 'Справочники',
	'ref_guide': 'Руководства',
	'reference': 'Справочная литература: прочее',
	'nonf_biography': 'Биографии и мемуары',
	'nonf_publicism': 'Публицистика',
	'nonf_criticism': 'Критика',
	'nonfiction': 'Документальное: прочее',
	'design': 'Искусство, дизайн',
	'adv_animal': 'Природа и животные',
	'religion': 'Религия',
	'religion_rel': 'Религия',
	'religion_esoterics': 'Эзотерика',
	'religion_self': 'Самосовершенствование',
	'religion': 'Религия и духовность: прочее',
	'sci_religion': 'Религиоведение',
	'humor_anecdote': 'Анекдоты',
	'humor_prose': 'Юмористическая проза',
	'humor_verse': 'Юмористические стихи',
	'humor': 'Юмор: Прочее',
	'home_cooking': 'Кулинария',
	'home_pets': 'Домашние животные',
	'home_crafts': 'Хобби, ремесла',
	'home_entertain': 'Развлечения',
	'home_health': 'Здоровье',
	'home_garden': 'Сад и огород',
	'home_diy': 'Сделай сам',
	'home_sport': 'Спорт',
	'home_sex': 'Эротика, секс',
	'home': 'Дом и семья: прочее'
}
