# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src\main\designer\preferencesdialog.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(443, 383)
        self.gridLayout_6 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_6.addWidget(self.buttonBox, 2, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tabGeneral = QtWidgets.QWidget()
        self.tabGeneral.setObjectName("tabGeneral")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tabGeneral)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.tabGeneral)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.deviceMountpointEdit = QtWidgets.QLineEdit(self.groupBox)
        self.deviceMountpointEdit.setObjectName("deviceMountpointEdit")
        self.horizontalLayout_7.addWidget(self.deviceMountpointEdit)
        self.deviceMountpointSelectButton = QtWidgets.QPushButton(self.groupBox)
        self.deviceMountpointSelectButton.setObjectName("deviceMountpointSelectButton")
        self.horizontalLayout_7.addWidget(self.deviceMountpointSelectButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.verticalLayout.addWidget(self.groupBox)
        self.libroModeGroup = QtWidgets.QGroupBox(self.tabGeneral)
        self.libroModeGroup.setEnabled(True)
        self.libroModeGroup.setObjectName("libroModeGroup")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.libroModeGroup)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.converterModeRadio = QtWidgets.QRadioButton(self.libroModeGroup)
        self.converterModeRadio.setObjectName("converterModeRadio")
        self.horizontalLayout_8.addWidget(self.converterModeRadio)
        self.libraryModeRadio = QtWidgets.QRadioButton(self.libroModeGroup)
        self.libraryModeRadio.setObjectName("libraryModeRadio")
        self.horizontalLayout_8.addWidget(self.libraryModeRadio)
        self.gridLayout_5.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.libroModeGroup)
        self.libraryOptionsGroup = QtWidgets.QGroupBox(self.tabGeneral)
        self.libraryOptionsGroup.setObjectName("libraryOptionsGroup")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.libraryOptionsGroup)
        self.verticalLayout_3.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.collectFilesCheck = QtWidgets.QCheckBox(self.libraryOptionsGroup)
        self.collectFilesCheck.setObjectName("collectFilesCheck")
        self.verticalLayout_3.addWidget(self.collectFilesCheck)
        self.label = QtWidgets.QLabel(self.libraryOptionsGroup)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.libraryRootEdit = QtWidgets.QLineEdit(self.libraryOptionsGroup)
        self.libraryRootEdit.setObjectName("libraryRootEdit")
        self.horizontalLayout.addWidget(self.libraryRootEdit)
        self.libraryRootSelectButton = QtWidgets.QPushButton(self.libraryOptionsGroup)
        self.libraryRootSelectButton.setObjectName("libraryRootSelectButton")
        self.horizontalLayout.addWidget(self.libraryRootSelectButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.label_2 = QtWidgets.QLabel(self.libraryOptionsGroup)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.filenamePatternEdit = QtWidgets.QComboBox(self.libraryOptionsGroup)
        self.filenamePatternEdit.setEditable(True)
        self.filenamePatternEdit.setObjectName("filenamePatternEdit")
        self.verticalLayout_3.addWidget(self.filenamePatternEdit)
        self.verticalLayout.addWidget(self.libraryOptionsGroup)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.tabWidget.addTab(self.tabGeneral, "")
        self.tabFb2c = QtWidgets.QWidget()
        self.tabFb2c.setObjectName("tabFb2c")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tabFb2c)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_17 = QtWidgets.QLabel(self.tabFb2c)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_5.addWidget(self.label_17)
        self.outputFormatCombo = QtWidgets.QComboBox(self.tabFb2c)
        self.outputFormatCombo.setObjectName("outputFormatCombo")
        self.horizontalLayout_5.addWidget(self.outputFormatCombo)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tabFb2c)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setOpenExternalLinks(True)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.converterPathEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.converterPathEdit.setObjectName("converterPathEdit")
        self.horizontalLayout_3.addWidget(self.converterPathEdit)
        self.converterPathSelectButton = QtWidgets.QPushButton(self.groupBox_2)
        self.converterPathSelectButton.setObjectName("converterPathSelectButton")
        self.horizontalLayout_3.addWidget(self.converterPathSelectButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.converterConfigEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.converterConfigEdit.setObjectName("converterConfigEdit")
        self.horizontalLayout_2.addWidget(self.converterConfigEdit)
        self.converterConfigSelectButton = QtWidgets.QPushButton(self.groupBox_2)
        self.converterConfigSelectButton.setObjectName("converterConfigSelectButton")
        self.horizontalLayout_2.addWidget(self.converterConfigSelectButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 41, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.tabWidget.addTab(self.tabFb2c, "")
        self.gridLayout_6.addWidget(self.tabWidget, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        self.libraryModeRadio.clicked.connect(Dialog.onLibroModeSelect)
        self.converterModeRadio.clicked.connect(Dialog.onLibroModeSelect)
        self.libraryRootSelectButton.clicked.connect(Dialog.onLibraryRootSelect)
        self.collectFilesCheck.clicked.connect(Dialog.onCollectFilesCheck)
        self.converterPathSelectButton.clicked.connect(Dialog.onConverterPathSelect)
        self.converterConfigSelectButton.clicked.connect(Dialog.onConfigFileSelect)
        self.deviceMountpointSelectButton.clicked.connect(Dialog.onDeviceMountpointSelect)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Preferences"))
        self.groupBox.setTitle(_translate("Dialog", "Reader device mountpoint"))
        self.deviceMountpointSelectButton.setText(_translate("Dialog", "Select"))
        self.libroModeGroup.setTitle(_translate("Dialog", "Libro mode"))
        self.converterModeRadio.setText(_translate("Dialog", "Converter"))
        self.libraryModeRadio.setText(_translate("Dialog", "Library manager"))
        self.libraryOptionsGroup.setTitle(_translate("Dialog", "Library manager options"))
        self.collectFilesCheck.setText(_translate("Dialog", "Collect files"))
        self.label.setText(_translate("Dialog", "Path to library root"))
        self.libraryRootSelectButton.setText(_translate("Dialog", "Select"))
        self.label_2.setText(_translate("Dialog", "File name pattern"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabGeneral), _translate("Dialog", "General"))
        self.label_17.setText(_translate("Dialog", "Output format:"))
        self.groupBox_2.setTitle(_translate("Dialog", "fb2converter"))
        self.label_3.setText(_translate("Dialog", "Path to executable"))
        self.label_5.setText(_translate("Dialog", "<a href=\"https://github.com/rupor-github/fb2converter/releases/latest\">Download</a>"))
        self.converterPathSelectButton.setText(_translate("Dialog", "Select"))
        self.label_4.setText(_translate("Dialog", "Configuration file"))
        self.converterConfigSelectButton.setText(_translate("Dialog", "Select"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFb2c), _translate("Dialog", "Convert"))


