# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src\main\designer\preferencesdialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(551, 493)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout.setSpacing(8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tabGeneral = QtWidgets.QWidget()
        self.tabGeneral.setObjectName("tabGeneral")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tabGeneral)
        self.verticalLayout_4.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.tabGeneral)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_18 = QtWidgets.QLabel(self.groupBox)
        self.label_18.setObjectName("label_18")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.styleCombo = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.styleCombo.sizePolicy().hasHeightForWidth())
        self.styleCombo.setSizePolicy(sizePolicy)
        self.styleCombo.setObjectName("styleCombo")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.styleCombo)
        self.label_19 = QtWidgets.QLabel(self.groupBox)
        self.label_19.setObjectName("label_19")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.accentColorCombo = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.accentColorCombo.sizePolicy().hasHeightForWidth())
        self.accentColorCombo.setSizePolicy(sizePolicy)
        self.accentColorCombo.setObjectName("accentColorCombo")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.accentColorCombo)
        self.verticalLayout_10.addLayout(self.formLayout)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.libroModeGroup = QtWidgets.QGroupBox(self.tabGeneral)
        self.libroModeGroup.setEnabled(True)
        self.libroModeGroup.setObjectName("libroModeGroup")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.libroModeGroup)
        self.verticalLayout_2.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.libraryModeRadio = QtWidgets.QRadioButton(self.libroModeGroup)
        self.libraryModeRadio.setObjectName("libraryModeRadio")
        self.verticalLayout_2.addWidget(self.libraryModeRadio)
        self.converterModeRadio = QtWidgets.QRadioButton(self.libroModeGroup)
        self.converterModeRadio.setObjectName("converterModeRadio")
        self.verticalLayout_2.addWidget(self.converterModeRadio)
        self.verticalLayout_4.addWidget(self.libroModeGroup)
        self.libraryOptionsGroup = QtWidgets.QGroupBox(self.tabGeneral)
        self.libraryOptionsGroup.setObjectName("libraryOptionsGroup")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.libraryOptionsGroup)
        self.verticalLayout_3.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.collectFilesCheck = QtWidgets.QCheckBox(self.libraryOptionsGroup)
        self.collectFilesCheck.setObjectName("collectFilesCheck")
        self.verticalLayout_3.addWidget(self.collectFilesCheck)
        self.label = QtWidgets.QLabel(self.libraryOptionsGroup)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.libraryRootEdit = QtWidgets.QLineEdit(self.libraryOptionsGroup)
        self.libraryRootEdit.setObjectName("libraryRootEdit")
        self.horizontalLayout.addWidget(self.libraryRootEdit)
        self.libraryRootSelectButton = QtWidgets.QPushButton(self.libraryOptionsGroup)
        self.libraryRootSelectButton.setObjectName("libraryRootSelectButton")
        self.horizontalLayout.addWidget(self.libraryRootSelectButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.label_2 = QtWidgets.QLabel(self.libraryOptionsGroup)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.filenamePatternEdit = QtWidgets.QComboBox(self.libraryOptionsGroup)
        self.filenamePatternEdit.setEditable(True)
        self.filenamePatternEdit.setObjectName("filenamePatternEdit")
        self.verticalLayout_3.addWidget(self.filenamePatternEdit)
        self.verticalLayout_4.addWidget(self.libraryOptionsGroup)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.tabWidget.addTab(self.tabGeneral, "")
        self.tabFb2c = QtWidgets.QWidget()
        self.tabFb2c.setObjectName("tabFb2c")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tabFb2c)
        self.verticalLayout_9.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_9.setSpacing(3)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_3 = QtWidgets.QLabel(self.tabFb2c)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_9.addWidget(self.label_3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.converterPathEdit = QtWidgets.QLineEdit(self.tabFb2c)
        self.converterPathEdit.setObjectName("converterPathEdit")
        self.horizontalLayout_3.addWidget(self.converterPathEdit)
        self.converterPathSelectButton = QtWidgets.QPushButton(self.tabFb2c)
        self.converterPathSelectButton.setObjectName("converterPathSelectButton")
        self.horizontalLayout_3.addWidget(self.converterPathSelectButton)
        self.verticalLayout_9.addLayout(self.horizontalLayout_3)
        self.label_4 = QtWidgets.QLabel(self.tabFb2c)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_9.addWidget(self.label_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.convertToFolderEdit = QtWidgets.QLineEdit(self.tabFb2c)
        self.convertToFolderEdit.setObjectName("convertToFolderEdit")
        self.horizontalLayout_6.addWidget(self.convertToFolderEdit)
        self.convertToFolderSelectButton = QtWidgets.QPushButton(self.tabFb2c)
        self.convertToFolderSelectButton.setObjectName("convertToFolderSelectButton")
        self.horizontalLayout_6.addWidget(self.convertToFolderSelectButton)
        self.verticalLayout_9.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_17 = QtWidgets.QLabel(self.tabFb2c)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_5.addWidget(self.label_17)
        self.outputFormatCombo = QtWidgets.QComboBox(self.tabFb2c)
        self.outputFormatCombo.setObjectName("outputFormatCombo")
        self.horizontalLayout_5.addWidget(self.outputFormatCombo)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout_9.addLayout(self.horizontalLayout_5)
        self.useCustomConfigRadio = QtWidgets.QRadioButton(self.tabFb2c)
        self.useCustomConfigRadio.setObjectName("useCustomConfigRadio")
        self.verticalLayout_9.addWidget(self.useCustomConfigRadio)
        self.customConfigGroup = QtWidgets.QGroupBox(self.tabFb2c)
        self.customConfigGroup.setObjectName("customConfigGroup")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.customConfigGroup)
        self.verticalLayout_6.setContentsMargins(-1, 6, 6, 6)
        self.verticalLayout_6.setSpacing(3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.configFileEdit = QtWidgets.QLineEdit(self.customConfigGroup)
        self.configFileEdit.setObjectName("configFileEdit")
        self.horizontalLayout_2.addWidget(self.configFileEdit)
        self.configFileSelectButton = QtWidgets.QPushButton(self.customConfigGroup)
        self.configFileSelectButton.setObjectName("configFileSelectButton")
        self.horizontalLayout_2.addWidget(self.configFileSelectButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.verticalLayout_9.addWidget(self.customConfigGroup)
        self.useDefaultConfigRadio = QtWidgets.QRadioButton(self.tabFb2c)
        self.useDefaultConfigRadio.setObjectName("useDefaultConfigRadio")
        self.verticalLayout_9.addWidget(self.useDefaultConfigRadio)
        self.configGroup = QtWidgets.QGroupBox(self.tabFb2c)
        self.configGroup.setObjectName("configGroup")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.configGroup)
        self.verticalLayout_5.setContentsMargins(-1, 6, 6, 6)
        self.verticalLayout_5.setSpacing(3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.configGroup)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.stylesheetFileEdit = QtWidgets.QLineEdit(self.configGroup)
        self.stylesheetFileEdit.setObjectName("stylesheetFileEdit")
        self.horizontalLayout_4.addWidget(self.stylesheetFileEdit)
        self.stylesheetFileSelectButton = QtWidgets.QPushButton(self.configGroup)
        self.stylesheetFileSelectButton.setObjectName("stylesheetFileSelectButton")
        self.horizontalLayout_4.addWidget(self.stylesheetFileSelectButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.insertHyphenCheck = QtWidgets.QCheckBox(self.configGroup)
        self.insertHyphenCheck.setObjectName("insertHyphenCheck")
        self.verticalLayout_5.addWidget(self.insertHyphenCheck)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.notesModeCombo = QtWidgets.QComboBox(self.configGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notesModeCombo.sizePolicy().hasHeightForWidth())
        self.notesModeCombo.setSizePolicy(sizePolicy)
        self.notesModeCombo.setObjectName("notesModeCombo")
        self.gridLayout_2.addWidget(self.notesModeCombo, 0, 1, 1, 1)
        self.apnxStyleCombo = QtWidgets.QComboBox(self.configGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.apnxStyleCombo.sizePolicy().hasHeightForWidth())
        self.apnxStyleCombo.setSizePolicy(sizePolicy)
        self.apnxStyleCombo.setObjectName("apnxStyleCombo")
        self.gridLayout_2.addWidget(self.apnxStyleCombo, 0, 4, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.configGroup)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 5, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.configGroup)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 0, 2, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_8 = QtWidgets.QLabel(self.configGroup)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.configGroup)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 1, 1, 1)
        self.titleFormatEdit = QtWidgets.QComboBox(self.configGroup)
        self.titleFormatEdit.setEditable(True)
        self.titleFormatEdit.setObjectName("titleFormatEdit")
        self.gridLayout.addWidget(self.titleFormatEdit, 1, 0, 1, 1)
        self.authorFormatEdit = QtWidgets.QComboBox(self.configGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.authorFormatEdit.sizePolicy().hasHeightForWidth())
        self.authorFormatEdit.setSizePolicy(sizePolicy)
        self.authorFormatEdit.setEditable(True)
        self.authorFormatEdit.setObjectName("authorFormatEdit")
        self.gridLayout.addWidget(self.authorFormatEdit, 1, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout)
        self.verticalLayout_9.addWidget(self.configGroup)
        spacerItem4 = QtWidgets.QSpacerItem(20, 41, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem4)
        self.tabWidget.addTab(self.tabFb2c, "")
        self.tabStk = QtWidgets.QWidget()
        self.tabStk.setObjectName("tabStk")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tabStk)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_10 = QtWidgets.QLabel(self.tabStk)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 0, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tabStk)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 0, 1, 1, 1)
        self.serverEdit = QtWidgets.QLineEdit(self.tabStk)
        self.serverEdit.setObjectName("serverEdit")
        self.gridLayout_3.addWidget(self.serverEdit, 1, 0, 1, 1)
        self.portEdit = QtWidgets.QLineEdit(self.tabStk)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.portEdit.sizePolicy().hasHeightForWidth())
        self.portEdit.setSizePolicy(sizePolicy)
        self.portEdit.setObjectName("portEdit")
        self.gridLayout_3.addWidget(self.portEdit, 1, 1, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_3)
        self.label_14 = QtWidgets.QLabel(self.tabStk)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_7.addWidget(self.label_14)
        self.passwordEdit = QtWidgets.QLineEdit(self.tabStk)
        self.passwordEdit.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.passwordEdit.setObjectName("passwordEdit")
        self.verticalLayout_7.addWidget(self.passwordEdit)
        self.label_12 = QtWidgets.QLabel(self.tabStk)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_7.addWidget(self.label_12)
        self.fromEmailEdit = QtWidgets.QLineEdit(self.tabStk)
        self.fromEmailEdit.setObjectName("fromEmailEdit")
        self.verticalLayout_7.addWidget(self.fromEmailEdit)
        self.label_13 = QtWidgets.QLabel(self.tabStk)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_7.addWidget(self.label_13)
        self.toEmailEdit = QtWidgets.QLineEdit(self.tabStk)
        self.toEmailEdit.setObjectName("toEmailEdit")
        self.verticalLayout_7.addWidget(self.toEmailEdit)
        spacerItem5 = QtWidgets.QSpacerItem(20, 221, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem5)
        self.tabWidget.addTab(self.tabStk, "")
        self.tabLog = QtWidgets.QWidget()
        self.tabLog.setObjectName("tabLog")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tabLog)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_15 = QtWidgets.QLabel(self.tabLog)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 0, 0, 1, 1)
        self.logModeCombo = QtWidgets.QComboBox(self.tabLog)
        self.logModeCombo.setObjectName("logModeCombo")
        self.gridLayout_4.addWidget(self.logModeCombo, 1, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.tabLog)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 1, 0, 1, 1)
        self.logLevelCombo = QtWidgets.QComboBox(self.tabLog)
        self.logLevelCombo.setObjectName("logLevelCombo")
        self.gridLayout_4.addWidget(self.logLevelCombo, 0, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem6, 0, 2, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_4)
        spacerItem7 = QtWidgets.QSpacerItem(20, 349, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem7)
        self.tabWidget.addTab(self.tabLog, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        self.libraryModeRadio.clicked.connect(Dialog.onLibroModeSelect)
        self.converterModeRadio.clicked.connect(Dialog.onLibroModeSelect)
        self.libraryRootSelectButton.clicked.connect(Dialog.onLibraryRootSelect)
        self.collectFilesCheck.clicked.connect(Dialog.onCollectFilesCheck)
        self.useCustomConfigRadio.clicked.connect(Dialog.onConvertConfigModeSelect)
        self.useDefaultConfigRadio.clicked.connect(Dialog.onConvertConfigModeSelect)
        self.convertToFolderSelectButton.clicked.connect(Dialog.onConvertToFolderSelect)
        self.converterPathSelectButton.clicked.connect(Dialog.onConverterPathSelect)
        self.configFileSelectButton.clicked.connect(Dialog.onConfigFileSelect)
        self.stylesheetFileSelectButton.clicked.connect(Dialog.onCSSFileSelect)
        self.styleCombo.currentIndexChanged['int'].connect(Dialog.onStyleChange)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Preferences"))
        self.groupBox.setTitle(_translate("Dialog", "Theme"))
        self.label_18.setText(_translate("Dialog", "Style:"))
        self.label_19.setText(_translate("Dialog", "Accent color:"))
        self.libroModeGroup.setTitle(_translate("Dialog", "Libro mode"))
        self.libraryModeRadio.setText(_translate("Dialog", "Library manager"))
        self.converterModeRadio.setText(_translate("Dialog", "Converter"))
        self.libraryOptionsGroup.setTitle(_translate("Dialog", "Library manager options"))
        self.collectFilesCheck.setText(_translate("Dialog", "Collect files"))
        self.label.setText(_translate("Dialog", "Path to library root"))
        self.libraryRootSelectButton.setText(_translate("Dialog", "Select"))
        self.label_2.setText(_translate("Dialog", "File name pattern"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabGeneral), _translate("Dialog", "General"))
        self.label_3.setText(_translate("Dialog", "Path to fb2c executable"))
        self.converterPathSelectButton.setText(_translate("Dialog", "Select"))
        self.label_4.setText(_translate("Dialog", "Convert to folder"))
        self.convertToFolderSelectButton.setText(_translate("Dialog", "Select"))
        self.label_17.setText(_translate("Dialog", "Output format:"))
        self.useCustomConfigRadio.setText(_translate("Dialog", "Use custom fb2c configuration file"))
        self.customConfigGroup.setTitle(_translate("Dialog", "Custom fb2c configuration file"))
        self.configFileSelectButton.setText(_translate("Dialog", "Select"))
        self.useDefaultConfigRadio.setText(_translate("Dialog", "Use this fb2c configuration"))
        self.configGroup.setTitle(_translate("Dialog", "fb2c configuration"))
        self.label_5.setText(_translate("Dialog", "CSS stylesheet file"))
        self.stylesheetFileSelectButton.setText(_translate("Dialog", "Select"))
        self.insertHyphenCheck.setText(_translate("Dialog", "Insert soft hyphen symbols"))
        self.label_6.setText(_translate("Dialog", "Notes mode:"))
        self.label_7.setText(_translate("Dialog", "Kindle page style:"))
        self.label_8.setText(_translate("Dialog", "Book title format"))
        self.label_9.setText(_translate("Dialog", "Book author format"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFb2c), _translate("Dialog", "fb2c"))
        self.label_10.setText(_translate("Dialog", "SMTP Server"))
        self.label_11.setText(_translate("Dialog", "SMTP Port"))
        self.label_14.setText(_translate("Dialog", "SMTP Password"))
        self.label_12.setText(_translate("Dialog", "From email"))
        self.label_13.setText(_translate("Dialog", "To (Kindle device) email"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabStk), _translate("Dialog", "Send to Kindle"))
        self.label_15.setText(_translate("Dialog", "Log level:"))
        self.label_16.setText(_translate("Dialog", "Log file mode:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLog), _translate("Dialog", "Log"))

